version: "3.10"
services:
  web:
    build: .
    image: aapq/photoshnaya_bot:latest
    restart: always
    network_mode: "host"
  redis:
    image: "redis:alpine"
    restart: always
    ports:
      - "6379:6379"

    volumes:
     - $PWD/redis-data:/var/lib/redis

    environment:
     - REDIS_REPLICATION_MODE=master
