[vote]
no_vote_yet = "Голосование не запущено."
not_enough_data = "У тебя сломанная ссылка, увы."
not_private_chat = "Голосовать можно только в приватном чате"
no_photos = "Недостаточно фотографий"
unexpected_error = "Ошибка в cmd_start, не сгенерировалось голосование"
already_voted = "Вы уже голосовали в этом челлендже, увы"

greeting_message_vote = "Голосуйте за фотографии!"


