[vote]
no_vote_yet = "Голосование не запущено."
wrong_link = "У тебя сломанная ссылка, увы."
not_private_chat = "Голосовать можно только в приватном чате"
no_photos = "Недостаточно фотографий"
unexpected_error = "Ошибка в cmd_start, не сгенерировалось голосование"

thanks_for_vote = "Спасибо, твой голос принят!"
already_voted = "Вы уже голосовали в этом челлендже, увы"
greeting_message_vote = "Голосуйте за фотографии!"



