[vote]
no_vote_yet = "Голосование не запущено."
vote_started = "Голосование запущено. Вот ссылка, отправьте ее в чат:"
no_username_bot = "Не получилось сгенерировать ссылку из-за отсутствия ника у бота, увы"
wrong_link = "У тебя сломанная ссылка, увы."
not_private_chat = "Голосовать можно только в приватном чате"
no_photos = "Недостаточно фотографий"
unexpected_error = "Ошибка в cmd_start, не сгенерировалось голосование"

thanks_for_vote = "Спасибо, твой голос принят!"
already_voted = "Вы уже голосовали в этом челлендже, увы"
greeting_message_vote = "Голосуйте за фотографии!"
no_winner = "Победителя нет. Никто не проголосовал."

[register_photo]
photo_registered = "Зарегистрировал фото."
photo_not_registered = "Уже регистрировал фото от тебя!"

[admin]
you_are_not_admin = """Ты не являешься администратором.\n
             Чтобы стать администратором в группе --
             добавь меня с правами админа в чат."""
choose_group = "Выберите группу"
choose_action = "Выберите ваше действие"
are_you_sure_S = "Точно хочешь начать голосование?"
are_you_sure_F =  "Точно хочешь завершить голосование?"
vote_end = 'Голосование завершено. Результаты ниже.'
no_photos_at_end = "Ошибка. Нет фоток!"


