[vote]
no_vote_yet = "Голосование не запущено."
vote_started = "Голосование запущено. Вот ссылка, отправьте ее в чат:"
no_username_bot = "Не получилось сгенерировать ссылку из-за отсутствия ника у бота, увы"
wrong_link = "У тебя сломанная ссылка, увы."
not_private_chat = "Голосовать можно только в приватном чате"
no_photos = "Недостаточно фотографий"
unexpected_error = "Ошибка в cmd_start, не сгенерировалось голосование"

thanks_for_vote = "Спасибо, твой голос принят!"
already_voted = "Вы уже голосовали в этом челлендже, увы"
greeting_message_vote = "Голосуйте за фотографии!"
no_winner = "Победителя нет. Никто не проголосовал."

[register_photo]
photo_registered = "Зарегистрировал фото."
photo_not_registered = "Уже регистрировал фото от тебя!"

[admin]
you_are_not_admin = """Ты не являешься администратором.\n
             Чтобы стать администратором в группе --
             добавь меня с правами админа в чат."""
choose_group = "Выберите группу"
choose_action = "Выберите ваше действие"
are_you_sure_S = "Точно хочешь начать голосование?"
are_you_sure_F =  "Точно хочешь завершить голосование?"
vote_end = 'Голосование завершено. Результаты ниже.'
no_photos_at_end = "Ошибка. Нет фоток!"
no_photos_at_start = "Нет фоток!"

#maybe move to db
[contest]
start_contest='''
Челлендж {num} — {theme}

Свежие фото присылайте в чат с сегодня:
 - до вечера {week}, {date_str};
 - можно несколько, но на конкурс пойдёт первая;
 - фото должно быть сделано в промежутке с {date_now} по {date_str};
 - под фото для конкурса пишите тег {theme}

Тема трактуется свободно, но:
 - без животных,
 - без нюдсов,
 - без жестокости.

В конце пришлю форму для голосования. Победитель ачивку в клубе✖️, а фоточка отправится на обложку чата.

Результаты предыдущего челленджа вот тут.
'''
create_greet_contest = "Пришли название для челленджа.\nДля отмены отправь слово отмена"
cancel_contest = "Отменил создание челленджа."
err = "Что-то у меня не вышло до конца. Но да ладно."

[add_admin]
create_greet_adm = "Перешли сюда сообщение от человека, которого ты хочешь сделать админом.\nУ него должен быть открыт профиль для пересылки.\n\nДля отмены отправь слово <code>отмена</code>"
add_adm = "Добавил админа."
no_adm = "Не увидел профиль, отменил добавление админа"
cancel_adm = "Отменил добавление админа"
err = "Произошла какая-то ошибка."

[delete_photo]
create_greet_del = "Удалить фото можно одним из следующих способов:\n<b>1) </b>Перешли сюда сообщение от человека, фото которого ты хочешь удалить.\n У него должен быть открыт профиль для пересылки.\n\n<b>2)</b> Пришли его юзернейм в формате @username\n\nДля отмены отправь слово <code>отмена</code>"
are_you_sure = "Посмотри, ты хочешь удалить эту фотку?"
del_photo = "Удалил фото."
no_user = "Не увидел профиль, отменил удаление фото"
cancel_del = "Отменил удаление фото."
no_understand = "Не понял ответ. Начни заново."
err = "Произошла какая-то ошибка."


